<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            [
                'id' => 1,
                'organization_id' => 1,
                'store_id' => 1,
                'category_id' => 1,
                'sei' => '澤村',
                'mei' => '勇太',
                'sei_kana' => 'サワムラ',
                'mei_kana' => 'ユウタ',
                'gender' => 1,
                'email' => 'sawamura1009@gmail.com',
                'birth' => '1988-10-09',
                'role' => 1,
                'password' => Hash::make('12345678'),
                'status' => 1,
                'created_at' => '2020-02-01 21:07:31',
                'updated_at' => '2020-02-01 21:07:31',
            ],
            [
                'id' => 2,
                'organization_id' => 1,
                'store_id' => 1,
                'category_id' => null,
                'sei' => '桜木',
                'mei' => 'くるみ',
                'sei_kana' => 'サクラギ',
                'mei_kana' => 'クルミ',
                'gender' => 2,
                'email' => 'sawamura1009+1@gmail.com',
                'birth' => '1988-10-09',
                'role' => 3,
                'password' => Hash::make('12345678'),
                'status' => 1,
                'created_at' => '2020-02-01 21:07:31',
                'updated_at' => '2020-02-01 21:07:31',
            ],
            [
                'id' => 3,
                'organization_id' => 1,
                'store_id' => 1,
                'category_id' => 1,
                'sei' => '山田',
                'mei' => '道正',
                'sei_kana' => null,
                'mei_kana' => null,
                'gender' => 1,
                'email' => 'sawamura1009+2@gmail.com',
                'birth' => '1988-10-09',
                'role' => 5,
                'password' => Hash::make('12345678'),
                'status' => 1,
                'created_at' => '2020-02-01 21:07:31',
                'updated_at' => '2020-02-01 21:07:31',
            ],
            [
                'id' => 4,
                'organization_id' => 1,
                'store_id' => 1,
                'category_id' => 1,
                'sei' => '佐々木',
                'mei' => '剛',
                'sei_kana' => 'ササキ',
                'mei_kana' => 'ツヨシ',
                'gender' => 1,
                'email' => null,
                'birth' => '2000-10-01',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2019-01-01 21:07:31',
                'updated_at' => '2019-01-01 21:07:31',
            ],
            [
                'id' => 5,
                'organization_id' => 1,
                'store_id' => 2,
                'category_id' => 1,
                'sei' => '田中',
                'mei' => '一郎',
                'sei_kana' => 'タナカ',
                'mei_kana' => 'イチロウ',
                'gender' => 1,
                'email' => null,
                'birth' => '2000-10-01',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2019-01-10 21:07:31',
                'updated_at' => '2019-01-10 21:07:31',
            ],
            [
                'id' => 6,
                'organization_id' => 1,
                'store_id' => 1,
                'category_id' => 1,
                'sei' => '小林',
                'mei' => '智',
                'sei_kana' => 'コバヤシ',
                'mei_kana' => 'サトシ',
                'gender' => 1,
                'email' => null,
                'birth' => '2000-10-01',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2019-02-10 21:07:31',
                'updated_at' => '2019-02-10 21:07:31',
            ],
            [
                'id' => 7,
                'organization_id' => 1,
                'store_id' => 1,
                'category_id' => 1,
                'sei' => '小林',
                'mei' => '智',
                'sei_kana' => 'コバヤシ',
                'mei_kana' => 'サトシ',
                'gender' => 1,
                'email' => null,
                'birth' => '2000-10-01',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2019-03-01 21:07:31',
                'updated_at' => '2019-03-01 21:07:31',
            ],
            [
                'id' => 8,
                'organization_id' => 1,
                'store_id' => 1,
                'category_id' => 1,
                'sei' => '木村',
                'mei' => '美代子',
                'sei_kana' => 'キムラ',
                'mei_kana' => 'ミヨコ',
                'gender' => 2,
                'email' => null,
                'birth' => '2000-10-01',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2019-03-01 21:07:31',
                'updated_at' => '2019-03-01 21:07:31',
            ],
            [
                'id' => 9,
                'organization_id' => 1,
                'store_id' => 1,
                'category_id' => 1,
                'sei' => '佐藤',
                'mei' => 'くるみ',
                'sei_kana' => 'サトウ',
                'mei_kana' => 'クルミ',
                'gender' => 2,
                'email' => null,
                'birth' => '2000-10-01',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2019-04-01 21:07:31',
                'updated_at' => '2019-04-01 21:07:31',
            ],
            [
                'id' => 10,
                'organization_id' => 1,
                'store_id' => 1,
                'category_id' => 2,
                'sei' => '小島',
                'mei' => '要',
                'sei_kana' => 'コジマ',
                'mei_kana' => 'カナメ',
                'gender' => 1,
                'email' => null,
                'birth' => '2012-01-01',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2019-05-01 21:07:31',
                'updated_at' => '2019-05-01 21:07:31',
            ],
            [
                'id' => 11,
                'organization_id' => 1,
                'store_id' => 1,
                'category_id' => 2,
                'sei' => '花井',
                'mei' => '陽介',
                'sei_kana' => 'ハナイ',
                'mei_kana' => 'ヨウスケ',
                'gender' => 1,
                'email' => null,
                'birth' => '2012-01-01',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2019-06-10 21:07:31',
                'updated_at' => '2019-06-10 21:07:31',
            ],
            [
                'id' => 12,
                'organization_id' => 1,
                'store_id' => 1,
                'category_id' => 2,
                'sei' => '坂田',
                'mei' => '圭介',
                'sei_kana' => 'サカタ',
                'mei_kana' => 'ケイスケ',
                'gender' => 1,
                'email' => null,
                'birth' => '2012-01-01',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2019-07-01 21:07:31',
                'updated_at' => '2019-07-01 21:07:31',
            ],
            [
                'id' => 13,
                'organization_id' => 1,
                'store_id' => 1,
                'category_id' => 2,
                'sei' => '窪田',
                'mei' => 'ゆり',
                'sei_kana' => 'クボタ',
                'mei_kana' => 'ユリ',
                'gender' => 2,
                'email' => null,
                'birth' => '2012-01-01',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2019-08-01 21:07:31',
                'updated_at' => '2019-08-01 21:07:31',
            ],
            [
                'id' => 14,
                'organization_id' => 1,
                'store_id' => 1,
                'category_id' => 2,
                'sei' => '米田',
                'mei' => '美紅',
                'sei_kana' => 'ヨネダ',
                'mei_kana' => 'ミク',
                'gender' => 2,
                'email' => null,
                'birth' => '2012-01-01',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2019-09-01 21:07:31',
                'updated_at' => '2019-09-01 21:07:31',
            ],
            [
                'id' => 15,
                'organization_id' => 1,
                'store_id' => 2,
                'category_id' => 1,
                'sei' => '本田',
                'mei' => '永吉',
                'sei_kana' => 'ホンダ',
                'mei_kana' => 'エイキチ',
                'gender' => 1,
                'email' => null,
                'birth' => '1989-02-01',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2019-10-01 21:07:31',
                'updated_at' => '2019-10-01 21:07:31',
            ],
            [
                'id' => 16,
                'organization_id' => 1,
                'store_id' => 2,
                'category_id' => 1,
                'sei' => '成海',
                'mei' => '太一',
                'sei_kana' => 'ナルミ',
                'mei_kana' => 'タイチ',
                'gender' => 1,
                'email' => null,
                'birth' => '1989-02-01',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2019-11-01 21:07:31',
                'updated_at' => '2019-11-01 21:07:31',
            ],
            [
                'id' => 17,
                'organization_id' => 1,
                'store_id' => 2,
                'category_id' => 1,
                'sei' => '松本',
                'mei' => '智則',
                'sei_kana' => 'マツモト',
                'mei_kana' => 'トモノリ',
                'gender' => 1,
                'email' => null,
                'birth' => '1989-02-01',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2019-12-01 21:07:31',
                'updated_at' => '2019-12-01 21:07:31',
            ],
            [
                'id' => 18,
                'organization_id' => 1,
                'store_id' => 2,
                'category_id' => 1,
                'sei' => '立花',
                'mei' => '美子',
                'sei_kana' => 'タチバナ',
                'mei_kana' => 'ヨシコ',
                'gender' => 2,
                'email' => null,
                'birth' => '2012-01-01',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2020-01-10 21:07:31',
                'updated_at' => '2020-01-10 21:07:31',
            ],
            [
                'id' => 19,
                'organization_id' => 1,
                'store_id' => 2,
                'category_id' => 1,
                'sei' => '杉山',
                'mei' => '綾子',
                'sei_kana' => 'スギヤマ',
                'mei_kana' => 'アヤコ',
                'gender' => 2,
                'email' => null,
                'birth' => '2012-01-01',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2020-02-01 21:07:31',
                'updated_at' => '2020-02-01 21:07:31',
            ],
            [
                'id' => 20,
                'organization_id' => 1,
                'store_id' => 2,
                'category_id' => 2,
                'sei' => '佐々木',
                'mei' => '貴教',
                'sei_kana' => 'ササキ',
                'mei_kana' => 'タカノリ',
                'gender' => 1,
                'email' => null,
                'birth' => '2016-03-10',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2020-02-01 21:07:31',
                'updated_at' => '2020-02-01 21:07:31',
            ],            [
                'id' => 21,
                'organization_id' => 1,
                'store_id' => 2,
                'category_id' => 2,
                'sei' => '三宅',
                'mei' => '一成',
                'sei_kana' => 'ミヤケ',
                'mei_kana' => 'イッセイ',
                'gender' => 1,
                'email' => null,
                'birth' => '2016-03-10',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2020-02-01 21:07:31',
                'updated_at' => '2020-02-01 21:07:31',
            ],
            [
                'id' => 22,
                'organization_id' => 1,
                'store_id' => 2,
                'category_id' => 2,
                'sei' => '宮澤',
                'mei' => '洋一',
                'sei_kana' => 'ミヤザワ',
                'mei_kana' => 'ヨウイチ',
                'gender' => 1,
                'email' => null,
                'birth' => '2016-03-10',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2020-03-01 21:07:31',
                'updated_at' => '2020-03-01 21:07:31',
            ],
            [
                'id' => 23,
                'organization_id' => 1,
                'store_id' => 2,
                'category_id' => 2,
                'sei' => '江古田',
                'mei' => '愛',
                'sei_kana' => 'エコタ',
                'mei_kana' => 'アイ',
                'gender' => 2,
                'email' => null,
                'birth' => '2016-03-10',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2020-04-10 21:07:31',
                'updated_at' => '2020-04-10 21:07:31',
            ],
            [
                'id' => 24,
                'organization_id' => 1,
                'store_id' => 2,
                'category_id' => 2,
                'sei' => '浜田',
                'mei' => 'えみ',
                'sei_kana' => 'ハマダ',
                'mei_kana' => 'エミ',
                'gender' => 2,
                'email' => null,
                'birth' => '2016-03-10',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2020-05-01 21:07:31',
                'updated_at' => '2020-05-01 21:07:31',
            ],
            [
                'id' => 25,
                'organization_id' => 1,
                'store_id' => 1,
                'category_id' => 1,
                'sei' => '中津川',
                'mei' => '淳',
                'sei_kana' => 'ナツカワ',
                'mei_kana' => 'アツシ',
                'gender' => 1,
                'email' => null,
                'birth' => '1978-08-24',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2020-06-01 21:07:31',
                'updated_at' => '2020-06-01 21:07:31',
            ],
            [
                'id' => 26,
                'organization_id' => 1,
                'store_id' => 1,
                'category_id' => 1,
                'sei' => '宇野',
                'mei' => '裕太',
                'sei_kana' => 'ウノ',
                'mei_kana' => 'ユウタ',
                'gender' => 1,
                'email' => null,
                'birth' => '1978-08-24',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2020-06-01 21:07:31',
                'updated_at' => '2020-06-01 21:07:31',
            ],
            [
                'id' => 27,
                'organization_id' => 1,
                'store_id' => 1,
                'category_id' => 1,
                'sei' => '井上',
                'mei' => '輝',
                'sei_kana' => 'イノウエ',
                'mei_kana' => 'アキラ',
                'gender' => 1,
                'email' => null,
                'birth' => '1978-08-24',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2020-07-01 21:07:31',
                'updated_at' => '2020-07-01 21:07:31',
            ],
            [
                'id' => 28,
                'organization_id' => 1,
                'store_id' => 1,
                'category_id' => 1,
                'sei' => '伊藤',
                'mei' => '陽子',
                'sei_kana' => 'イトウ',
                'mei_kana' => 'ヨウコ',
                'gender' => 2,
                'email' => null,
                'birth' => '1978-08-24',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2020-07-01 21:07:31',
                'updated_at' => '2020-07-01 21:07:31',
            ],
            [
                'id' => 29,
                'organization_id' => 1,
                'store_id' => 1,
                'category_id' => 1,
                'sei' => '青木',
                'mei' => 'さや',
                'sei_kana' => 'アオキ',
                'mei_kana' => 'サヤ',
                'gender' => 2,
                'email' => null,
                'birth' => '1978-08-24',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2020-08-10 21:07:31',
                'updated_at' => '2020-08-10 21:07:31',
            ],
            [
                'id' => 30,
                'organization_id' => 1,
                'store_id' => 1,
                'category_id' => 2,
                'sei' => '藤本',
                'mei' => '順',
                'sei_kana' => 'フジモト',
                'mei_kana' => 'ジュン',
                'gender' => 1,
                'email' => null,
                'birth' => '2012-06-22',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2020-09-01 21:07:31',
                'updated_at' => '2020-09-01 21:07:31',
            ],
            [
                'id' => 31,
                'organization_id' => 1,
                'store_id' => 1,
                'category_id' => 2,
                'sei' => '原西',
                'mei' => '三郎',
                'sei_kana' => 'ハラニシ',
                'mei_kana' => 'サブロウ',
                'gender' => 1,
                'email' => null,
                'birth' => '2012-06-22',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2020-09-10 21:07:31',
                'updated_at' => '2020-09-10 21:07:31',
            ],
            [
                'id' => 32,
                'organization_id' => 1,
                'store_id' => 1,
                'category_id' => 2,
                'sei' => '山岸',
                'mei' => '太郎',
                'sei_kana' => 'ヤマギシ',
                'mei_kana' => 'タロウ',
                'gender' => 1,
                'email' => null,
                'birth' => '2012-06-22',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2020-09-01 21:07:31',
                'updated_at' => '2020-09-01 21:07:31',
            ],
            [
                'id' => 33,
                'organization_id' => 1,
                'store_id' => 1,
                'category_id' => 2,
                'sei' => '佐藤',
                'mei' => '奈々',
                'sei_kana' => 'サトウ',
                'mei_kana' => 'ナナ',
                'gender' => 2,
                'email' => null,
                'birth' => '2012-06-22',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2020-09-01 21:07:31',
                'updated_at' => '2020-09-01 21:07:31',
            ],
            [
                'id' => 34,
                'organization_id' => 1,
                'store_id' => 1,
                'category_id' => 2,
                'sei' => '市海道',
                'mei' => '沙耶',
                'sei_kana' => 'イチカイドウ',
                'mei_kana' => 'サヤ',
                'gender' => 2,
                'email' => null,
                'birth' => '2012-06-22',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2020-09-01 21:07:31',
                'updated_at' => '2020-09-01 21:07:31',
            ],
            [
                'id' => 35,
                'organization_id' => 1,
                'store_id' => 1,
                'category_id' => 2,
                'sei' => '萩原',
                'mei' => '沙耶',
                'sei_kana' => 'ハギワラ',
                'mei_kana' => 'サヤ',
                'gender' => 2,
                'email' => null,
                'birth' => '2012-06-22',
                'role' => 9,
                'password' => null,
                'status' => 2,
                'created_at' => '2020-02-01 21:07:31',
                'updated_at' => '2020-02-01 21:07:31',
            ],
            [
                'id' => 36,
                'organization_id' => 2,
                'store_id' => 4,
                'category_id' => 3,
                'sei' => '萩原',
                'mei' => '淳一',
                'sei_kana' => 'ハギワラ',
                'mei_kana' => 'ジュンイチ',
                'gender' => 1,
                'email' => null,
                'birth' => '2012-06-22',
                'role' => 9,
                'password' => null,
                'status' => 1,
                'created_at' => '2020-06-10 21:07:31',
                'updated_at' => '2020-02-01 21:07:31',
            ],
        ]);
    }
}
