version: "3.7"

services:
  mysql:
    image: mysql:5.7.31
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lt_local
      MYSQL_USER: lt_user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - 33060:3306
  db-testing:
    image: mysql:5.7.31
    container_name: db-testing
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database-test
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    tmpfs:
      - /var/lib/mysql
      - /var/log/mysql
    ports:
      - 3307:3306
  phpfpm:
    build:
      context: .
      dockerfile: ./docker/phpfpm/Dockerfile
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    restart: always
  nginx:
    image: nginx:1.17.10-alpine
    depends_on:
      - phpfpm
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

volumes:
  mysql-data:
    driver: local
