version: "3.7"

services:
    phpfpm:
        build:
            context: .
            dockerfile: ./docker/phpfpm/Dockerfile
        depends_on:
            - mysql
        volumes:
            - .:/var/www/html
            - /var/www/html/vendor
        restart: always
    nginx:
        image: nginx:1.17.10-alpine
        depends_on:
            - phpfpm
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
