name: Laravel

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: cp .env.ci .env
      - name: composer install
        if: steps.cache.outputs.cache-hit != 'true'
        run: composer install -n --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      # - name: migrate
      #   run: php artisan migrate:fresh --seed
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      # - name: unit test
      #   run: ./vendor/bin/phpunit
